### ISSUE TITLE
Neighbor count and cutoff radius

### ISSUE THREAD

**Issue by lwang-astro** [FDPS/PIKG#1] opened 2020-08-19 09:32 UTC
I want to generate a force kernel for Fugaku with the linear cutoff function and neighbor count.
All particles have the same cutoff radius rcut and when dr<rcut, force is calculated by using rcut, otherwise using dr.
dr = max(dr, rcut)

Besides, each particle have their neighbor radius rs, the neighbor count is done by
if (dr< max(rsi, rsj)) nnbi++; 
where rsi and rsj are neighbor radii of i and j particles.

Is it possible to generate such kind of condition based codes by using PIKG?

**Comment by subarutaro** [comment] 2020-08-19 09:52
I think it is possible.
The PIKG code maybe like below:
```
EPI F64vec xi:pos
EPI F64 rsi:rsi

EPJ F64vec xj:pos
EPJ F64 mj:mass
EPJ F64 rsj:rsj

FORCE F64vec acc:acc
FORCE F64 pot:pot
FORCE S64 nnbi:nnbi

F64 eps2
F64 rcut2

rij = xi - xj
r2 = max(rcut2, rij * rij + eps2)
r_inv  = rsqrt(r2)
r2_inv = r_inv * r_inv
mr_inv  = mj * r_inv
mr3_inv = r2_inv * mr_inv
if r2 < max(rsi*rsi,rsj*rsj)
  nnbi  += 1
endif
acc -= mr3_inv * rij
pot -= mr_inv
```

**Comment by lwang-astro** [comment] 2020-08-19 11:21
Thank you! I will try this code.

**Comment by subarutaro** [comment] 2020-08-19 11:25
Please check the code is correct with --coversion-type reference which generate relatively human-readable. I already tried the code and compilable code was generated.

**Comment by subarutaro** [comment] 2020-08-19 11:31
And please note that current PIKG does not generate "optimized" code for A64FX  only with --conversion-type A64FX. You need to add pragma of loop fission and loop unroll to the code with options. If you have question for this, please ask here or launch new issue.

**Comment by lwang-astro** [comment] 2020-08-21 07:30
I tried this way
```
./bin/pikg -i input -o kernel.hpp --conversion-type A64FX
```
where input is the file contain the code you sent before. 
The log is 
```
input file: input
output file name: kernel.hpp
conversion type: A64FX
size of EPI member is 64, # of elemennts are 4
Traceback (most recent call last):
        11: from ../../../bin/pikg:2:in `<main>'
        10: from ../../../bin/pikg:2:in `require_relative'
         9: from /home/lwang/code/PIKG/src/parserdriver.rb:1485:in `<top (required)>'
         8: from /home/lwang/code/PIKG/src/parserdriver.rb:907:in `generate_optimized_code'
         7: from /home/lwang/code/PIKG/src/parserdriver.rb:855:in `kernel_body'
         6: from /home/lwang/code/PIKG/src/parserdriver.rb:855:in `each'
         5: from /home/lwang/code/PIKG/src/parserdriver.rb:856:in `block in kernel_body'
         4: from /home/lwang/code/PIKG/src/intermediate_exp_class.rb:37:in `convert_to_code'
         3: from /home/lwang/code/PIKG/src/intermediate_exp_class.rb:37:in `each'
         2: from /home/lwang/code/PIKG/src/intermediate_exp_class.rb:38:in `block in convert_to_code'
         1: from /home/lwang/code/PIKG/src/intermediate_exp_class.rb:825:in `convert_to_code'
code/PIKG/src/common.rb:278:in `get_num_elem': wrong number of arguments (given 1, expected 2) (ArgumentError)
```
What is the problem here?

**Comment by subarutaro** [comment] 2020-08-21 07:38
Sorry, it is a bug in PIKG. I already fixed and pushed it to develop branch. Please try to use develop branch for now.
This bug fix will be merged to master branch in next release.

**Comment by lwang-astro** [comment] 2020-08-21 07:45
Thank you, now I can successfully generate the code, but I found a bug in the code:
 35            rsi = __fkg_tmp_epi.v0;
 36            xi.v0 = __fkg_tmp_epi.v0;
 37            xi.v1 = __fkg_tmp_epi.v1;
 38            xi.v2 = __fkg_tmp_epi.v2;
It looks like the rsi is not correctly given.

**Comment by subarutaro** [comment] 2020-08-21 07:56
What looks like bug?
The rsi and xi is temporall loaded to __fkg_tpm_epi using structure load and assigned to rsi and xi.
```
svfloat64x4_t __fkg_tmp_epi;

__fkg_tmp_epi = svld4_f64(pg0,((double*)&epi[i]));
svfloat64x3_t xi;

svfloat64_t rsi;

rsi = __fkg_tmp_epi.v0;
xi.v0 = __fkg_tmp_epi.v0;
xi.v1 = __fkg_tmp_epi.v1;
xi.v2 = __fkg_tmp_epi.v2;
svfloat64x3_t acc;
```

**Comment by subarutaro** [comment] 2020-08-21 07:59
sorry, I missed the rsi = __fkg_tmp_epi."v0";
I will check.

**Comment by subarutaro** [comment] 2020-08-21 08:15
I fixed the bug and pushed to develop branch.
Pleas try.

**Comment by lwang-astro** [comment] 2020-10-20 07:36
I have another question about the multi precision case.
Now I have EPI, EPJ and Force in F64, but want to calculate in F32 in the kernel.
First I create the tempera array of x, y, z, mass, rs of Epi and Epj in F32 and copy the data from F64 type input.
Then calculate force using the kernel from PIKG.
But I found the following part of code
```
static uint32_t index_gather_load0[16] = {0,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75};
svuint32_t vindex_gather_load0 = svld1_u32(pg0,index_gather_load0);
acc.v0 = svld1_gather_u32index_f32(pg0,((float*)&force[i].acc.x),vindex_gather_load0);
```
Here the original type of force[i].acc is F64. Will this part of code can work correctly?
Should I first create F32 array of acc, pot like epi, epj and then copy the result of F32 back to F64 after the calculation finish?

**Comment by subarutaro** [comment] 2020-10-20 07:45
Could you give us the PIKG source?

In multi precision mode, you have to write the type conversion explicitly.
For example,
```
rij = EPI.pos - EPJ.pos
r2 = rij * rij
rinv = rsqrt(r2)
mrinv = EPJ.mass * rinv
mrinv3 = mrinv * rinv * rinv
FORCE.acc.x += to_f64(mrinv3 * rij.x)
FORCE.acc.y += to_f64(mrinv3 * rij.y)
FORCE.acc.z += to_f64(mrinv3 * rij.z)
```
if types of EPI and EPJ are F32 and type of FORCE is F64.

**Comment by lwang-astro** [comment] 2020-10-21 00:00
This is the same code that you provided to me before
```
EPI F32vec xi:pos
EPI F32 rsi:rsi

EPJ F32vec xj:pos
EPJ F32 mj:mass
EPJ F32 rsj:rsj

FORCE F32vec acc:acc
FORCE F32 pot:pot
FORCE S32 nnbi:nnbi

F32 eps2
F32 rcut2

rij = xi - xj
r2 = max(rcut2, rij * rij + eps2)
r_inv  = rsqrt(r2)
r2_inv = r_inv * r_inv
mr_inv  = mj * r_inv
mr3_inv = r2_inv * mr_inv
if r2 < max(rsi*rsi,rsj*rsj)
  nnbi  += 1
  endif
  acc -= mr3_inv * rij
  pot -= mr_inv
```
What is the part that slow down the performance, is it the data transfer between F64 and F32? In such case, I will try to use pure F64 codes because my epi, epj and force all use F64

**Comment by subarutaro** [comment] 2020-10-21 00:07
I do not think the data transfer make kernel slow.

There are two choices.
(1) make F32 array of F32 and copy the F32 results to F64 original array, as you mentioned.
(2) use pure F64 code by replacing F32 to F64 in the PIKG source above.

**Comment by lwang-astro** [comment] 2020-10-21 00:08
So will the first solution faster than the second case?

**Comment by lwang-astro** [comment] 2020-10-21 00:10
Besides, when I pull the update of pikg,
I got an error when run 
```
./bin/pikg -i input.64 -o kernel_64.hpp --conversion-type A64FX

input file: input.64
output file name: kernel_64.hpp
conversion type: A64FX
/home/lwang/code/PIKG/src/intermediate_exp_class.rb:1518: warning: deprecated Object#=~ is called on Expression; it always returns nil
/home/lwang/code/PIKG/src/intermediate_exp_class.rb:1518: warning: deprecated Object#=~ is called on Expression; it always returns nil
/home/lwang/code/PIKG/src/intermediate_exp_class.rb:1518: warning: deprecated Object#=~ is called on Expression; it always returns nil
Traceback (most recent call last):
        17: from ../../../bin/pikg:2:in `<main>'
        16: from ../../../bin/pikg:2:in `require_relative'
        15: from /home/lwang/code/PIKG/src/parserdriver.rb:1688:in `<top (required)>'
        14: from /home/lwang/code/PIKG/src/parserdriver.rb:985:in `generate_optimized_code'
        13: from /home/lwang/code/PIKG/src/parserdriver.rb:931:in `kernel_body'
        12: from /home/lwang/code/PIKG/src/parserdriver.rb:931:in `each'
        11: from /home/lwang/code/PIKG/src/parserdriver.rb:932:in `block in kernel_body'
        10: from /home/lwang/code/PIKG/src/intermediate_exp_class.rb:37:in `convert_to_code'
         9: from /home/lwang/code/PIKG/src/intermediate_exp_class.rb:37:in `each'
         8: from /home/lwang/code/PIKG/src/intermediate_exp_class.rb:38:in `block in convert_to_code'
         7: from /home/lwang/code/PIKG/src/intermediate_exp_class.rb:37:in `convert_to_code'
         6: from /home/lwang/code/PIKG/src/intermediate_exp_class.rb:37:in `each'
         5: from /home/lwang/code/PIKG/src/intermediate_exp_class.rb:38:in `block in convert_to_code'
         4: from /home/lwang/code/PIKG/src/intermediate_exp_class.rb:140:in `convert_to_code'
         3: from /home/lwang/code/PIKG/src/intermediate_exp_class.rb:140:in `zip'
         2: from /home/lwang/code/PIKG/src/intermediate_exp_class.rb:142:in `block in convert_to_code'
         1: from /home/lwang/code/PIKG/src/intermediate_exp_class.rb:784:in `convert_to_code'
/home/lwang/code/PIKG/src/intermediate_exp_class.rb:784:in `/': nil can't be coerced into Integer (TypeError)
```

**Comment by subarutaro** [comment] 2020-10-21 00:14
Sorry, currently the A64FX kernel generator has a bug.
I am trying to fix...Please wait.

**Comment by lwang-astro** [comment] 2020-11-05 11:49
I have updated the PIKG today and test the new version of generated code with A64FX.
I got compile error on Fugaku (I use mpiFCC):

 in expansion of macro "to_int" at line 438 of "./src/force_fugaku.hpp"
      PS::S64   to_int(PS::F64 op){return (PS::S64)op;}

"./src/force_fugaku.hpp", line 544: error: too many arguments in invocation of macro "to_int"
      svint64_t  to_int(svbool_t pg,svfloat64_t op){ return svcvt_s64_f64_z(pg,op);}

"./src/force_fugaku.hpp", line 187: error: no suitable conversion function from "svfloat32x3_t" to "svfloat32_t" exists
                  r2 = max(pg0,svdup_n_f32(rcut2),svadd_f32_z(pg0,svmul_f32_z(pg0,rij,rij),svdup_n_f32(eps2)));

"./src/force_fugaku.hpp", line 187: error: no instance of overloaded function "CalcForceEpEpWithLinearCutoffFugaku::max" matches the argument list
            argument types are: (svbool_t, svfloat32_t, svfloat32_t)
                  r2 = max(pg0,svdup_n_f32(rcut2),svadd_f32_z(pg0,svmul_f32_z(pg0,rij,rij),svdup_n_f32(eps2)));

"./src/force_fugaku.hpp", line 188: error: no instance of overloaded function "CalcForceEpEpWithLinearCutoffFugaku::rsqrt" matches the argument list
            argument types are: (svbool_t, svfloat32_t)
                  r_inv = rsqrt(pg0,r2);

"./src/force_fugaku.hpp", line 194: warning: variable "pg1" was set but never used
                      svbool_t pg1;

**Comment by lwang-astro** [comment] 2020-11-05 12:14
The generated code relate to this error is:
```
                svfloat32x3_t rij;
                svfloat32_t r2;
                svfloat32_t r_inv;
                svfloat32_t r2_inv;
                svfloat32_t mr_inv;
                svfloat32_t mr3_inv;
                svint32_t __fkg_tmp0;

                rij.v0 = svsub_f32_z(pg0,xi.v0,xj.v0);
                rij.v1 = svsub_f32_z(pg0,xi.v1,xj.v1);
                rij.v2 = svsub_f32_z(pg0,xi.v2,xj.v2);

                r2 = max(pg0,svdup_n_f32(rcut2),svadd_f32_z(pg0,svmul_f32_z(pg0,rij,rij),svdup_n_f32(eps2)));
```

**Comment by subarutaro** [comment] 2020-11-05 12:35
PIKG does not allow to pass the sentence (rij*rij + eps2) as an argument to function.
Please try
r2 = rij*rij + eps2
r2_cut = max(r2,rcut2)
r_inv = rsqrt(r2_cut)

**Comment by lwang-astro** [comment] 2020-11-05 13:10
Thanks. Now this part works. The acc and pot seems correct. But the neighbor count seems wrong.
For a test case, the correct neighbor number should be zero, but the kernel return value seems random
```
Neighbor diff: i=0 nosimd 0 fugaku -22080
Neighbor diff: i=2 nosimd 0 fugaku 20
Neighbor diff: i=4 nosimd 0 fugaku -23376
Neighbor diff: i=6 nosimd 0 fugaku 20
Neighbor diff: i=7 nosimd 0 fugaku 16384
Neighbor diff: i=8 nosimd 0 fugaku 20
Neighbor diff: i=9 nosimd 0 fugaku 65535
```

Here is the neighbor part of the code
```
                {
                    svbool_t pg2;
                    svbool_t pg1;
                    pg2 = svcmplt_f32(pg0,r2,max(pg0,svmul_f32_z(pg0,rsi,rsi),svmul_f32_z(pg0,rsj,rsj)));
                    pg1 = pg2;

                    __fkg_tmp0 = svadd_s32_z(pg2,nnbi,svdup_n_s32(1));
                    nnbi = svsel_s32(pg2,__fkg_tmp0,nnbi);;
                }
```

**Comment by lwang-astro** [comment] 2020-11-05 13:12
Here pg1 seems not used.

**Comment by subarutaro** [comment] 2020-11-05 13:16
pg1 is only used if the code includes elsif or else.
I think your code currently like below:
```
if r2 < max(rsi*rsi,rsj*rsj)
  nnbi  += 1
endif
acc -= mr3_inv * rij
pot -= mr_inv
```
while the correct code is
```
if r2_cut < max(rsi*rsi,rsj*rsj)
  nnbi  += 1
endif
acc -= mr3_inv * rij
pot -= mr_inv
```

**Comment by lwang-astro** [comment] 2020-11-05 13:28
I changed the r2 to r2_cut but the result does not change.
```
            {                                                                                                                |                    pg2 = svcmplt_f32(pg0,r2_cut,max(pg0,svmul_f32_z(pg0,rsi,rsi),svmul_f32_z(pg0,rsj,rsj)));
                svint32_t __fkg_tmp_accum;                                                                                   |                    pg1 = pg2;
                uint32_t index_gather_load7[16] = {0,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75};                           |
                svuint32_t vindex_gather_load7 = svld1_u32(svptrue_b32(),index_gather_load7);                                |                    __fkg_tmp0 = svadd_s32_z(pg2,nnbi,svdup_n_s32(1));
                __fkg_tmp_accum = svld1_gather_u32index_s32(svptrue_b32(),((int*)&force_loc[i+0].nnb),vindex_gather_load7);  |                    nnbi = svsel_s32(pg2,__fkg_tmp0,nnbi);;
                __fkg_tmp_accum = svadd_s32_z(svptrue_b32(),__fkg_tmp_accum,nnbi);                                           |                }
                uint32_t index_scatter_store3[16] = {0,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75};                         |
                svuint32_t vindex_scatter_store3 = svld1_u32(svptrue_b32(),index_scatter_store3);                            |                acc.v0 = svmsb_f32_z(svptrue_b32(),mr3_inv,rij.v0,acc.v0);
                svst1_scatter_u32index_s32(svptrue_b32(),((int*)&force_loc[i+0].nnb),vindex_scatter_store3,__fkg_tmp_accum);\|                acc.v1 = svmsb_f32_z(svptrue_b32(),mr3_inv,rij.v1,acc.v1);
}                                                                                                                            |                acc.v2 = svmsb_f32_z(svptrue_b32(),mr3_inv,rij.v2,acc.v2);

``` 
Here is the gether part

**Comment by subarutaro** [comment] 2020-11-05 13:33
Does the FORCE class only consists of acc, pot, nnbi and declared in this order?
PIKG assumes the FORCE class definition as
```
class FORCE{
  PIKG::F32vec acc;
  PIKG::F32       pot;
  PIKG::S32       nnbi;
};
```

**Comment by lwang-astro** [comment] 2020-11-05 13:41
struct FORCE32{
    PIKG::F32vec acc;
    PIKG::F32 pot;
    PIKG::S32 nnb;
};
Yes here is my definitation, only nnbi is changed to nnb, I have made the consistent change of the name in the code

**Comment by subarutaro** [comment] 2020-11-05 13:46
Thanks. Class definition seems ok.
Is it possible to give me the whole source code? I want to try by myself.

**Comment by lwang-astro** [comment] 2020-11-05 13:56
https://github.com/lwang-astro/PeTar/blob/master/src/force_fugaku.hpp

**Comment by subarutaro** [comment] 2020-11-05 14:04
Thanks. I successfully builded an executable and confirmed same result above.

**Comment by subarutaro** [comment] 2020-11-05 15:06
you use force_loc without initialization.
add code below before entering double loop.
```
for(i=0;i<ni_act;i++){
  force_loc[i].acc = 0.f;
  force_loc[i].pot = 0.f;
  force_loc[i].nnb = 0;
}
```

**Comment by subarutaro** [comment] 2020-11-05 15:12
PIKG assumes that all the FORCE member variables are initialized.
In the store part (you mentioned as gather part), PIKG loads the each FORCE member and then accumulate the result and store.
Thus, FORCE member must have initial value.

**Comment by lwang-astro** [comment] 2020-11-06 01:09
Thank you. I added the initial part, but it seems the neighbor number returned from fugaku is always zero. 
```
...
Neighbor diff: i=979 nosimd 1 fugaku 0
Neighbor diff: i=980 nosimd 1 fugaku 0
Neighbor diff: i=981 nosimd 1 fugaku 0
Neighbor diff: i=982 nosimd 1 fugaku 0
Neighbor diff: i=983 nosimd 1 fugaku 0
Neighbor diff: i=984 nosimd 1 fugaku 0
Neighbor diff: i=985 nosimd 1 fugaku 0
Neighbor diff: i=986 nosimd 1 fugaku 0
Neighbor diff: i=987 nosimd 1 fugaku 0
Neighbor diff: i=988 nosimd 1 fugaku 0
Neighbor diff: i=989 nosimd 1 fugaku 0
Neighbor diff: i=990 nosimd 1 fugaku 0
Neighbor diff: i=991 nosimd 1 fugaku 0
Neighbor diff: i=992 nosimd 1 fugaku 0
Neighbor diff: i=993 nosimd 1 fugaku 0
Neighbor diff: i=994 nosimd 1 fugaku 0
Neighbor diff: i=995 nosimd 1 fugaku 0
Neighbor diff: i=996 nosimd 1 fugaku 0
Neighbor diff: i=997 nosimd 1 fugaku 0
Neighbor diff: i=998 nosimd 1 fugaku 0
Neighbor diff: i=999 nosimd 1 fugaku 0
 EP_32bit SP_32bit

Fugaku diff max: 0.000587758 Pot diff max: 2.03529e-06
NNB: 1 997
NNB: 2 3
<NNB>: fugaku: 0
```
I have updated the test code. You can see this result if you run the new test code.

**Comment by subarutaro** [comment] 2020-11-06 01:32
I think this is because you modified the code from
```
if r2 < max(rsi*rsi,rsj*rsj)
  nnbi  += 1
endif
```
to
```
if r2_cut < max(rsi*rsi,rsj*rsj)
  nnbi  += 1
endif
```
This modification excludes the particle itself from nnbi.

**Comment by lwang-astro** [comment] 2020-11-06 01:57
Thank you. This fix my problem. Now the neighbor count is correct

**Closed** 2020-11-06 01:59 UTC
